<Project>
    <ItemGroup>
        <CompilerVisibleProperty Include="UseRootNamespaceForBuildInformation" />
        <CompilerVisibleProperty Include="AllowProjectDirectoryBuildOutput" />
        <CompilerVisibleProperty Include="Configuration" />
        <CompilerVisibleProperty Include="MSBuildProjectName" />
        <CompilerVisibleProperty Include="SOURCE_DATE_EPOCH" />
    </ItemGroup>
</Project>
